"""Add is_ai_selected to messages and enforce sender type

Revision ID: 97f614ae231f
Revises: 4087fb024c3d
Create Date: 2025-02-22 10:21:44.336470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f614ae231f'
down_revision: Union[str, None] = '4087fb024c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_selected', sa.Boolean(), nullable=True)) # Thêm cột is_ai_selected
    op.create_check_constraint('sender_type_check', 'messages', "sender IN ('user', 'system')") # Thêm CheckConstraint cho sender
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sender_type_check', 'messages', type_='check') # Xóa CheckConstraint
    op.drop_column('messages', 'is_selected') # Xóa cột is_ai_selected
    # ### end Alembic commands ###
